import { Exercise } from './types';

// Helper to ensure exercises exist at build time, preventing runtime crashes.
const findExerciseById = (id: string): Exercise => {
  const exercise = EXERCISES.find(e => e.id === id);
  if (!exercise) {
    throw new Error(`Initialization Error: Exercise with id "${id}" not found.`);
  }
  return exercise;
};

export const DAILY_CHALLENGES: Exercise[] = [
  {
    id: 'push-up-challenge',
    name: "Today's Challenge",
    description: 'Do your plan before 9:00 AM',
    instructions: 'Keep your body in a straight line from head to heels. Lower your chest to the floor, then push back up.',
    difficulty: 'Intermediate',
    duration: 5,
    calories: 50,
    image: 'https://images.pexels.com/photos/3076516/pexels-photo-3076516.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    metValue: 8.0,
  },
];

export const PROGRESS_WORKOUT: Exercise = {
    id: 'lower-body-progress',
    name: 'Lower Body',
    description: 'Cardio - 10 mins',
    instructions: "Focus on squats, lunges, and calf raises.",
    difficulty: 'Advanced',
    duration: 10,
    calories: 538,
    image: 'https://images.pexels.com/photos/2204196/pexels-photo-2204196.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    metValue: 6.0,
};

export const EXERCISES: Exercise[] = [
  {
    id: 'push-up',
    name: 'Push-ups',
    description: 'A classic bodyweight exercise targeting the chest, shoulders, and triceps.',
    instructions: '1. Start in a high plank position with hands slightly wider than shoulder-width apart. \n2. Keep your body in a straight line from head to heels. \n3. Lower your chest towards the floor by bending your elbows. \n4. Push back up to the starting position.',
    aiInstructions: "Analyze the user's push-up form. Key points: Is their body in a straight line from head to heels (no sagging hips or piking)? Are their elbows tucking in towards their body (around 45 degrees) rather than flaring out to 90 degrees? Is their chest getting close to the floor for full range of motion? Note any hip sag as a high importance issue.",
    difficulty: 'Intermediate',
    duration: 10,
    calories: 100,
    image: 'https://images.pexels.com/photos/416405/pexels-photo-416405.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    angleLandmarks: ['leftShoulder', 'leftElbow', 'leftWrist'],
    angleThresholds: { up: 160, down: 90 },
    metValue: 8.0,
    category: 'Upper body',
  },
  {
    id: 'squat',
    name: 'Squats',
    description: 'A fundamental lower body exercise that works the quads, hamstrings, and glutes.',
    instructions: '1. Stand with your feet shoulder-width apart, toes pointing slightly out. \n2. Keep your chest up and back straight. \n3. Lower your hips as if sitting in a chair, aiming to get your thighs parallel to the floor. \n4. Keep your knees behind your toes. \n5. Push through your heels to return to the starting position.',
    aiInstructions: "Analyze the user's squat form. Key points: Are their hips descending to be parallel with or below their knees (depth)? Is their back straight and chest up (posture)? Are their knees tracking over their feet and not caving inwards (knee valgus)? Is their weight in their heels? Provide specific feedback on each of these points if incorrect.",
    difficulty: 'Beginner',
    duration: 10,
    calories: 80,
    image: 'https://images.pexels.com/photos/791763/pexels-photo-791763.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'],
    angleThresholds: { up: 160, down: 90 },
    metValue: 5.5,
    category: 'Lower body',
  },
  {
    id: 'bicep-curl',
    name: 'Bicep Curls',
    description: 'An isolation exercise for the biceps. Can be done with dumbbells or resistance bands.',
    instructions: '1. Stand or sit with a dumbbell in each hand, palms facing forward. \n2. Keep your elbows tucked at your sides. \n3. Curl the weights up towards your shoulders without swinging your body. \n4. Squeeze your biceps at the top. \n5. Slowly lower the weights back to the starting position.',
    aiInstructions: "Analyze the user's bicep curl form. Key points: Are their elbows staying pinned to their sides and not moving forward? Is the movement controlled, without using momentum or swinging the body? Is there a full range of motion, from full extension at the bottom to a full contraction at the top? Provide feedback on avoiding momentum.",
    difficulty: 'Beginner',
    duration: 10,
    calories: 60,
    image: 'https://images.pexels.com/photos/1431283/pexels-photo-1431283.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    angleLandmarks: ['leftShoulder', 'leftElbow', 'leftWrist'],
    angleThresholds: { up: 150, down: 70 },
    metValue: 3.5,
    category: 'Upper body',
  },
  { 
    id: 'lunges', 
    name: 'Lunges', 
    description: 'Works legs and glutes.', 
    instructions: 'Step forward with one leg and lower your hips until both knees are bent at a 90-degree angle.', 
    difficulty: 'Beginner', 
    duration: 10, 
    calories: 90, 
    image: 'https://images.pexels.com/photos/6456303/pexels-photo-6456303.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    aiInstructions: "Analyze lunge form. Key points: Is the front knee tracking over the ankle and not past the toes? Is the back knee dropping close to the ground? Is the torso upright and stable, not leaning forward? Is the front foot flat on the ground? Provide feedback on knee alignment and torso stability.", 
    angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'], 
    angleThresholds: { up: 160, down: 95 }, 
    metValue: 5.0,
    category: 'Lower body',
  },
  { 
    id: 'crunches', 
    name: 'Crunches', 
    description: 'Abdominal exercise.', 
    instructions: 'Lie on your back, knees bent. Lift your upper body towards your knees.', 
    difficulty: 'Beginner', 
    duration: 5, 
    calories: 40, 
    image: 'https://images.pexels.com/photos/3764395/pexels-photo-3764395.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    aiInstructions: "Analyze crunch form. Key points: Is the user lifting their shoulder blades off the floor? Is the lower back staying on the ground? Is the chin tucked slightly, not straining the neck? Provide feedback on range of motion and neck position.",
    angleLandmarks: ['leftShoulder', 'leftHip', 'leftKnee'], 
    angleThresholds: { up: 130, down: 90 }, 
    metValue: 4.0,
    category: 'Upper body',
  },
  { 
    id: 'tricep-dips', 
    name: 'Tricep Dips', 
    description: 'Targets the triceps.', 
    instructions: 'Use a bench or chair. Lower your body until elbows are at 90 degrees.', 
    difficulty: 'Intermediate', 
    duration: 5, 
    calories: 50, 
    image: 'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    aiInstructions: "Analyze tricep dip form. Key points: Are the elbows pointing straight back and not flaring out? Is the user lowering until their elbows are at about a 90-degree angle? Is the back close to the bench or chair? Provide feedback on elbow position and depth.",
    angleLandmarks: ['leftShoulder', 'leftElbow', 'leftWrist'], 
    angleThresholds: { up: 160, down: 90 }, 
    metValue: 4.5,
    category: 'Upper body',
  },
   { 
    id: 'jumping-jacks', 
    name: 'Jumping Jacks', 
    description: 'Full body cardio exercise.', 
    instructions: 'Jump to a position with legs spread wide and hands touching overhead. Return to a position with feet together and arms at the sides.', 
    difficulty: 'Beginner', 
    duration: 10, 
    calories: 100, 
    image: 'https://images.pexels.com/photos/7031705/pexels-photo-7031705.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    aiInstructions: "Analyze jumping jack form. The 'down' phase is feet together, arms at sides. The 'up' phase is feet apart, arms overhead. Key points: Are the arms going all the way up? Are the jumps light and quick? Is there coordination between arm and leg movements? Provide feedback on rhythm and range of motion.",
    angleLandmarks: ['leftWrist', 'leftShoulder', 'leftHip'],
    angleThresholds: { up: 160, down: 30 },
    metValue: 8.0,
    category: 'Cardio',
  },
  { 
    id: 'plank', 
    name: 'Plank', 
    description: 'Core strength exercise.', 
    instructions: 'Hold a push-up position on your forearms.', 
    difficulty: 'Beginner', 
    duration: 1, 
    calories: 10, 
    image: 'https://images.pexels.com/photos/3112004/pexels-photo-3112004.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    aiInstructions: "Analyze plank form. This is an isometric hold, so there is no 'up' or 'down' phase. Give feedback on form only. Key points: Is the body in a straight line from head to heels? Are the hips not sagging or raised too high? Is the core engaged? Use 'neutral' phase and provide feedback on body alignment.",
    metValue: 2.5,
    category: 'Upper body',
  },
];


export const PLAN_WORKOUTS: Exercise[] = [
    {
        id: 'lower-body-plan',
        name: 'Lower body workout',
        description: "Cardio, 5 exercises",
        instructions: "Focus on squats, lunges, and calf raises.",
        difficulty: 'Advanced',
        duration: 30,
        calories: 220,
        image: 'https://images.pexels.com/photos/1552252/pexels-photo-1552252.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        category: 'Lower body',
        metValue: 6.0,
        subExercises: [
            { ...findExerciseById('squat'), type: 'reps', sets: 3, reps: 12 },
            { ...findExerciseById('lunges'), type: 'reps', sets: 3, reps: 10 },
            { id: 'step-ups', name: 'Step Ups', description: 'Leg strengthening exercise.', instructions: 'Step up onto a platform with one foot, then bring the other foot up. Step back down.', difficulty: 'Beginner', duration: 10, calories: 100, image: 'https://images.pexels.com/photos/3768916/pexels-photo-3768916.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', aiInstructions: "Analyze step-up form. Key points: Is the user driving through the heel of the leading foot? Is the movement controlled, especially on the way down? Is the back straight and core engaged? Provide feedback on control and posture.", type: 'reps', sets: 3, reps: 12, angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'], angleThresholds: { up: 160, down: 90 }, metValue: 6.0 },
            { id: 'wall-sits', name: 'Wall Sits', description: 'Isometric exercise for quads.', instructions: 'Lean against a wall with your knees bent at a 90-degree angle, as if sitting in a chair.', difficulty: 'Intermediate', duration: 2, calories: 20, image: 'https://images.pexels.com/photos/7005238/pexels-photo-7005238.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', aiInstructions: "Analyze wall-sit form. This is an isometric hold, so there is no 'up' or 'down' phase. Give feedback on form only. Key points: Are the thighs parallel to the ground? Is the back flat against the wall? Are the knees at a 90-degree angle? Use 'neutral' phase and provide feedback.", type: 'time', sets: 3, holdTime: 45, metValue: 3.8 },
            { id: 'calf-raises', name: 'Calf Raises', description: 'Strengthens calf muscles.', instructions: 'Stand with feet flat on the floor. Raise your heels up as high as you can, then lower.', difficulty: 'Beginner', duration: 5, calories: 30, image: 'https://images.pexels.com/photos/6740632/pexels-photo-6740632.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', aiInstructions: "Analyze calf-raise form. Key points: Is the user rising onto the balls of their feet as high as possible? Is there a brief pause at the top? Is the descent slow and controlled? Provide feedback on range of motion and control.", type: 'reps', sets: 3, reps: 20, metValue: 3.0 },
        ]
    },
    {
        id: 'upper-body-plan',
        name: 'Upper body workout',
        description: "Strength, 5 exercises",
        instructions: "Combination of push-ups, pull-ups, and bicep curls.",
        difficulty: 'Intermediate',
        duration: 20,
        calories: 150,
        image: 'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        category: 'Upper body',
        metValue: 5.5,
        subExercises: [
            { ...findExerciseById('plank'), type: 'time', sets: 3, holdTime: 60 },
            { ...findExerciseById('push-up'), type: 'reps', sets: 3, reps: 10 },
            { ...findExerciseById('crunches'), type: 'reps', sets: 3, reps: 15 },
            { ...findExerciseById('bicep-curl'), type: 'reps', sets: 3, reps: 12 },
            { ...findExerciseById('tricep-dips'), type: 'reps', sets: 3, reps: 10 },
        ]
    },
    {
        id: 'cardio-plan',
        name: 'Cardio workout',
        description: "Heart, 5 exercises",
        instructions: "Get your heart rate up with these high-energy exercises.",
        difficulty: 'Intermediate',
        duration: 15,
        calories: 180,
        image: 'https://images.pexels.com/photos/863977/pexels-photo-863977.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        category: 'Cardio',
        metValue: 8.0,
        subExercises: [
            { ...findExerciseById('jumping-jacks'), type: 'time', sets: 1, holdTime: 60 },
            { id: 'mountain-climbers', name: 'Mountain Climbers', description: 'Cardio exercise that also works the core.', instructions: 'In a plank position, alternate bringing your knees towards your chest.', difficulty: 'Intermediate', duration: 5, calories: 60, image: 'https://images.pexels.com/photos/6455850/pexels-photo-6455850.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', aiInstructions: "Analyze mountain climber form. This is a continuous movement, so phase detection is less critical. Focus on form. Key points: Is the back flat and hips level (like a plank)? Are the knees driving towards the chest? Is the pace consistent? Use 'neutral' phase and provide feedback on maintaining a strong plank position.", type: 'time', sets: 1, holdTime: 45, metValue: 8.5 },
            { id: 'jump-rope', name: 'Jump Rope', description: 'Classic cardio workout.', instructions: 'Use a skipping rope. Jump as the rope passes under your feet.', difficulty: 'Beginner', duration: 10, calories: 120, image: 'https://images.pexels.com/photos/4327031/pexels-photo-4327031.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', aiInstructions: "Analyze jump rope form. The 'up' phase is in the air, 'down' is on the ground. Key points: Are the jumps small and efficient? Is the user rotating the rope from the wrists, not the shoulders? Is the posture upright? Provide feedback on jump height and wrist rotation.", type: 'time', sets: 1, holdTime: 120, metValue: 11.8 },
            { id: 'high-knees', name: 'High Knees', description: 'Intense cardio exercise.', instructions: 'Run in place, bringing your knees up as high as possible.', difficulty: 'Intermediate', duration: 5, calories: 70, image: 'https://images.pexels.com/photos/7031706/pexels-photo-7031706.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', aiInstructions: "Analyze high knees form. This is a continuous movement. Focus on form. Key points: Are the knees being lifted to hip height? Is the user landing on the balls of their feet? Is the torso upright? Use 'neutral' phase and give feedback on knee height.", type: 'time', sets: 1, holdTime: 45, metValue: 10.0 },
            { id: 'butt-kicks', name: 'Butt Kicks', description: 'Cardio warm-up exercise.', instructions: 'Run in place, trying to kick your glutes with your heels.', difficulty: 'Beginner', duration: 5, calories: 50, image: 'https://images.pexels.com/photos/3768911/pexels-photo-3768911.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', aiInstructions: "Analyze butt kicks form. This is a continuous movement. Focus on form. Key points: Are the heels actually kicking or coming close to the glutes? Is the posture upright? Are the arms pumping? Use 'neutral' phase and give feedback on heel-to-glute distance.", type: 'time', sets: 1, holdTime: 60, metValue: 7.0 },
        ]
    },
];